!!adeuni.group.ec.algorithm.configuration.yml.YamlConfiguration
#the representation class used for this evolutionary algorithm
representation: PermutationRepresentation


#Section: population structure
#------------------------------------------------------------------------------
#| elite(option) | parent survivors | offspring survivors | immigrate(option) |
#------------------------------------------------------------------------------
#population = elite + parent survivors + offspring survivors + immigrate
#eliteSize:           is the number of best individuals who will be passed directly to next generation
#parentSurvivorSize:  is the number of last generations selected by parentSurvivorSelectionRoulette
#                        who will survive to the next generation
#offspringSize:       is the number of individuals be reproduced every iteration(offsprings)
#offspringSurvivorSize: is the number of offsprings who survived, not everyone survive, important:
#                          offspringSurvivorSize should no bigger than offspringSize
#immigrateSize:       is the number of new random generated individuals
#
#NOTICE: only integer allowed

eliteSize: 2
parentSurvivorSize: 18
offspringSize: 70
offspringSurvivorSize: 30
immigrateSize: 0


#Section: variation roulette configuration
#variation: put the implemented variation operator class here
#
#NOTICE: only double allowed for weight
variationRouletteCellList:
  - variation: PermutationPMXCrossover
    weight: 5.0
  - variation: PermutationOrderCrossover
    weight: 4.0


parentSelectionRouletteCellList:
  - selection: BestSelection
    weight: 5.0


parentSurvivorSelectionRouletteCellList:
  - selection: BestSelection
    weight: 5.0


offspringSurvivorSelectionRouletteCellList:
  - selection: BestSelection
    weight: 5.0


#Section: termination criteria pool
terminationCriteriaPool:
  - criterion: IterationTerminationCriterion
    maxIterationRound: 2000
  - criterion: ExecutionTimeTerminationCriterion
    maxExecutionTime: 14400000
